blank_issues_enabled: true
contact_links:
  - name: ‚ùì Support
    url: https://wpwax.com/contact/
    about: For any support or feature request, please head over to our official support channel.
  - name: Documentation
    url: https://wpwax.com/docs/post-grid-carousel-ultimate/
    about: To know more about Post Grid, Slider & Carousel Ultimate, please check out our official documentation.
